#! /bin/bash

export HOME=/home/jw
export RAILS_ENV=development

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


cd /projects/mustmodify/blog

nvm use
rails s -p 35811 -b 0.0.0.0
